Movie view design
essamMohamedFahmi/iMovie pull request #2
Opened 2022-01-10 12:00 UTC by MorsySoker

Add MoviesView 
Connected ProfileView with the NavigationBar 
Add dismiss button to ProfileView
Can't Log in with essam -- root  
show password button doesn't work
don't refactor anything plz just leave notes

2022-01-12 19:31 UTC, essamMohamedFahmi requested changes

2022-01-12 19:31 UTC, essamMohamedFahmi commented on iMovie/Scenes/Movies/MoviesView.swift
> +}
Format this file, recheck spaces

2022-01-12 19:31 UTC, essamMohamedFahmi commented on iMovie/Scenes/Movies/MoviesView.swift
> +    // MARK: - Private Methods
We put methods at the bottom, not on the top

2022-01-12 19:31 UTC, essamMohamedFahmi commented on iMovie/Views/ContentPickerView.swift
> +enum ContentCriteria: String, CaseIterable {
Awesome but this should be called "MovieCategory" or something like that

2022-01-12 19:31 UTC, essamMohamedFahmi commented on iMovie/Views/ContentPickerView.swift
> +    private func currentSelector() -> some View {
Good separation but cases are very large, try separate cases in other methods ✌🏽

2022-01-12 19:31 UTC, essamMohamedFahmi commented on iMovie/Views/NavigationBarView.swift
> +    var body: some View {
Divide these views into computed properties

2022-01-13 10:11 UTC, essamMohamedFahmi requested changes

2022-01-13 10:11 UTC, essamMohamedFahmi commented on iMovie/Views/NavigationBarView.swift
> +    private var hamburgerMenuButton: some View {
Please look at login module and see how we create view computed properties

2022-01-13 10:11 UTC, essamMohamedFahmi commented on iMovie/Views/NavigationBarView.swift
> +    private var hamburgerMenuButton: some View {
We put them above body and mark is View Components please just follow same structure

2022-01-13 10:11 UTC, essamMohamedFahmi commented on iMovie/Views/CategoryPickerView.swift
> +    private func displayContent() -> some View {
Why this is method not computed property and also caller method should be before called one - journal style clean code

2022-01-13 10:12 UTC, essamMohamedFahmi commented
Do not resolve things, just push edits

2022-01-14 13:08 UTC, MorsySoker commented on iMovie/Views/NavigationBarView.swift
> +    var body: some View {
done

2022-01-14 22:54 UTC, essamMohamedFahmi approved these changes

2022-01-14 22:54 UTC, essamMohamedFahmi commented on iMovie/Scenes/Movies/MoviesView.swift
> +    var topSafeAreaInsets: CGFloat {
Does this need to be a computed property and get calculated every time or it needs to be calculated the first time only?

2022-01-14 23:07 UTC, essamMohamedFahmi commented
Please squash and merge with the title "Add movies view"

2022-01-14 23:08 UTC, merged